name: E2E tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Use Node.js 19.1
      uses: actions/setup-node@v3
      with:
        node-version: 19.1
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser init
      run: rfbrowser init
      
    - name: Run Playwright tests
      uses: microsoft/playwright-github-action@v1.5.7
            
    - name: Run E2E Tests
      run: robot -d ./results -v HEADLESS:true -v BROWSER:chromium tests
      
